/*!
 * アクション用定義
 * @author teco
 * @since 2012.05.25
 */

#ifndef _INCLUDED_SIDE_ACTION_TYPES_H_
#define _INCLUDED_SIDE_ACTION_TYPES_H_

#define SIDE_ACTION_GRAVITY (0.65f)
#define SIDE_ACTION_GRAVITY_WEAK (0.5f)
#define SIDE_ACTION_GRAVITY_MAX (0.65f*30.0f)

#include "common/collision/action_collision.h"

const TbFloat32 SIDE_ACTION_JUMP_VELO = -5.1f;

// レイヤー
enum ActionActorLayer
{
    SIDE_ACTION_ACTOR_LAYER_PRE , 
    SIDE_ACTION_ACTOR_LAYER_PLAYER ,
    SIDE_ACTION_ACTOR_LAYER_POST ,
    SIDE_ACTION_ACTOR_LAYER_MAX 
};

enum SideActionCollisionLayer
{
    SIDE_ACTION_COLLISION_LAYER_OTHER = ActionCollision::LAYER_DEFAULT ,
    SIDE_ACTION_COLLISION_LAYER_PLAYER , 
    SIDE_ACTION_COLLISION_LAYER_PLAYER_OBJECT,
    SIDE_ACTION_COLLISION_LAYER_PLAYER_SUB ,
    SIDE_ACTION_COLLISION_LAYER_TO_PLAYER , 
    SIDE_ACTION_COLLISION_LAYER_OBJECT , 
    SIDE_ACTION_COLLISION_LAYER_OBJECT_2 ,
    SIDE_ACTION_COLLISION_LAYER_ENEMY  ,
    SIDE_ACTION_COLLISION_LAYER_KEY    ,
    SIDE_ACTION_COLLISION_LAYER_KEY_TARGET    ,
    SIDE_ACTION_COLLISION_LAYER_GOAL   ,
};

enum SideActionPhysicsLayer
{
    SIDE_ACTION_PHYSICS_LAYER_NORMAL , // 通常
    SIDE_ACTION_PHYSICS_LAYER_AREA   , // エリア
};

// イベント
enum SideActionEvent
{
    SIDE_ACTION_EVENT_JUMP        , // ジャンプ
    SIDE_ACTION_EVENT_DEAD        , // 死亡
    SIDE_ACTION_EVENT_GAMEOVER    , // ゲームオーバー
    SIDE_ACTION_EVENT_WARP        , // 瞬間移動
    SIDE_ACTION_EVENT_WARP_INIT_POS , // 瞬間移動
    SIDE_ACTION_EVENT_SWITCH_ON   , // スイッチオン
    SIDE_ACTION_EVENT_SWITCH_OFF  , // スイッチオフ
    SIDE_ACTION_EVENT_KEYBOX_ON   , // 鍵箱
    SIDE_ACTION_EVENT_ANGLE       , // 角度
    SIDE_ACTION_EVENT_ACTIVATE    , // アクティブ化
    SIDE_ACTION_EVENT_F32         , // float値
    SIDE_ACTION_EVENT_REGISTER    , // 登録
    SIDE_ACTION_EVENT_UNREGISTER  , // 登録解除
    SIDE_ACTION_EVENT_ALIVE       , // 生存通知
    SIDE_ACTION_EVENT_RETURN      , // 復帰
    SIDE_ACTION_EVENT_LEVEL_UP    , // レベルアップ
    SIDE_ACTION_EVENT_RESET_JUMP  , // ジャンプリセット
    SIDE_ACTION_EVENT_KEY_END     , // 鍵の役目終了
    SIDE_ACTION_EVENT_RESULT      , // 結果
    SIDE_ACTION_EVENT_SLEEP      , // 睡眠
    SIDE_ACTION_EVENT_WAKEUP      , // 起こす
    SIDE_ACTION_EVENT_SUSPEND    , // アクティブ化
    SIDE_ACTION_EVENT_GET_PLAYERINDEX ,
};

#endif
